# Site settings
title: Jeremys' Website
baseurl: ""
twitter_username: jeremycgray
github_username:  jeremycg
stackoverflow_link: users/3760920/jeremycg
stackoverflow_name: jeremycg
owner_email: jeremycgray@gmail.com
linkedin: jeremycgray

# Build settings
markdown: kramdown
